INSERT INTO MCUMovie (movieName, moviePosterURL, movieTrailerURL, movieReleaseDate)
VALUES ('Iron Man', '/img/movies/Iron_Man.jpg', 'https://www.youtube.com/embed/bK_Y5LjSJ-Y', '2008-04-30'),
       ('The Incredible Hulk', '/img/movies/The-Incredible-Hulk.jpg', 'https://www.youtube.com/embed/xbqNb2PFKKA', '2008-06-13'),
       ('Iron Man 2', '/img/movies/Iron_Man_2.jpg', 'https://www.youtube.com/embed/FNQowwwwYa0', '2010-04-28'),
       ('Thor', '/img/movies/Thor.jpg', 'https://www.youtube.com/embed/JOddp-nlNvQ', '2011-04-27'),
       ('Captain America: The First Avenger', '/img/movies/CaptainAmericaTheFirstAvenger.jpg', 'https://www.youtube.com/embed/JerVrbLldXw', '2011-07-22'),
       ('The Avengers', '/img/movies/The_avengers.jpg', 'https://www.youtube.com/embed/eOrNdBpGMv8', '2012-04-24'),
       ('Iron Man 3', '/img/movies/Iron_Man_3.jpg', 'https://www.youtube.com/embed/_UMVJ3wRqDg', '2013-04-24'),
       ('Thor: The Dark World', '/img/movies/Thor_Un_Mundo_Oscuro_Poster.jpg', 'https://www.youtube.com/embed/7p7rocHEecE', '2013-10-30'),
       ('Captain America: The Winter Soldier', '/img/movies/Captain_America_The_Winter_Soldier.jpg', 'https://www.youtube.com/embed/7SlILk2WMTI', '2014-03-26'),
       ('Guardians of the Galaxy', '/img/movies/GuardiansoftheGalaxy.jpg', 'https://www.youtube.com/embed/d96cjJhvlMA', '2014-08-01'),
       ('Avengers: Age of Ultron', '/img/movies/Avengers_Age_Of_Ultron.jpg', 'https://www.youtube.com/embed/MZoO8QVMxkk', '2015-04-22'),
       ('Ant-Man', '/img/movies/Ant-Man.png', 'https://www.youtube.com/embed/IEVE3KSKQ0o', '2015-07-14'),
       ('Captain America: Civil War', '/img/movies/Captain_America_Civil_War.jpg', 'https://www.youtube.com/embed/43NWzay3W4s', '2016-04-27'),
       ('Doctor Strange', '/img/movies/DrStrange.jpg', 'https://www.youtube.com/embed/HSzx-zryEgM', '2016-10-25'),
       ('Guardians of the Galaxy Vol. 2', '/img/movies/GuardiansoftheGalaxyV2.jpg', 'https://www.youtube.com/embed/sMTntxvok1M', '2017-04-25'),
       ('Spider-Man: Homecoming', '/img/movies/Spider_Man_Homecoming.jpg', 'https://www.youtube.com/embed/rk-dF1lIbIg', '2017-07-07'),
       ('Thor: Ragnarok', '/img/movies/Thor_Ragnarok.jpg', 'https://www.youtube.com/embed/ue80QwXMRHg', '2017-10-24'),
       ('Black Panther', '/img/movies/Black_Panther.jpg', 'https://www.youtube.com/embed/xjDjIWPwcPU', '2018-02-13'),
       ('Avengers: Infinity War', '/img/movies/Avengers_Infinity_war.jpg', 'https://www.youtube.com/embed/6ZfuNTqbHE8', '2018-04-27'),
       ('Ant-Man and the Wasp', '/img/movies/Ant-Man_and_the_Wasp.jpg', 'https://www.youtube.com/embed/8_rTIAOohas', '2018-07-04'),
       ('Captain Marvel', '/img/movies/CaptainMarvel.jpg', 'https://www.youtube.com/embed/Z1BCujX3pw8', '2019-03-08'),
       ('Avengers: Endgame', '/img/movies/Avengers_Endgame.jpg', 'https://www.youtube.com/embed/hA6hldpSTF8', '2019-04-26'),
       ('Spider-Man: Far From Home', '/img/movies/Spidar_Man_Far_From_Home.jpg', 'https://www.youtube.com/embed/VUFmhKpZKlE', '2019-07-02');